# Generated by Django 3.2.9 on 2022-10-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=200)),
                ('guide_branch', models.CharField(max_length=200)),
                ('guide_email', models.EmailField(max_length=254)),
                ('guide_mobile', models.PositiveIntegerField()),
                ('guide_specilization', models.CharField(choices=[('AI/ML', 'AI/ML'), ('Cloud', 'Cloud'), ('Blockchain', 'Blockchain'), ('Cyber Security', 'Cyber Security'), ('HCI', 'HCI'), ('Robotics', 'Robotics')], max_length=50)),
            ],
        ),
    ]
