# Generated by Django 3.2.9 on 2022-10-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='guide_branch',
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_department',
            field=models.CharField(choices=[('CS', 'CS'), ('IT', 'IT'), ('ENTC', 'ENTC'), ('MECH', 'MECH')], default='CS', max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_mobile',
            field=models.CharField(max_length=20),
        ),
    ]
