# Generated by Django 3.2.9 on 2022-10-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20221013_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_department',
            field=models.CharField(choices=[('CS', 'CS'), ('IT', 'IT'), ('ENTC', 'ENTC'), ('MECH', 'MECH')], default='Select Department', max_length=200),
        ),
    ]
