# Generated by Django 3.2.9 on 2022-10-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_alter_guide_guide_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_department',
            field=models.CharField(choices=[('Select Department', 'Select Department'), ('CS', 'CS'), ('IT', 'IT'), ('ENTC', 'ENTC'), ('MECH', 'MECH')], default='Select Department', max_length=200),
        ),
    ]
