# Generated by Django 3.2.9 on 2022-10-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_guide_guide_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_department',
            field=models.CharField(choices=[('CS', 'CS'), ('IT', 'IT'), ('ENTC', 'ENTC'), ('MECH', 'MECH')], max_length=200),
        ),
    ]
