# Generated by Django 3.2.9 on 2022-10-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_no', models.PositiveIntegerField(default=0)),
                ('student_name', models.CharField(max_length=200)),
                ('student_div', models.CharField(max_length=10)),
                ('student_branch', models.CharField(max_length=200)),
                ('student_roll', models.PositiveIntegerField(default=0)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_mobile', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
