# Generated by Django 3.2.9 on 2022-10-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20221013_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_branch',
            field=models.CharField(choices=[('CS', 'CS'), ('IT', 'IT'), ('ENTC', 'ENTC'), ('MECH', 'MECH')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_div',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10),
        ),
    ]
