# Generated by Django 3.2.9 on 2022-10-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='student.student')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='student.student')),
                ('member3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='student.student')),
                ('member4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member4', to='student.student')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='student.student')),
            ],
        ),
    ]
